GarageReturn/GarageReturn/Models/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GarageReturn.Models
{
    public class EditViewModel
    {

        public EditViewModel()
        {

        }
        public EditViewModel(int id, string color, string brand, string model, int numberOfWheels , string regNum)
        {
             Id  = id;
            Color= color;
            Brand = brand;
            Model = model;
            NumberOfWheels = numberOfWheels;
            RegNum = regNum;
        }

        public int Id { get; set; }
        public string Color { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int NumberOfWheels { get; set; }
        public string RegNum { get; set; }
    }
   
}

GarageReturn/GarageReturn/Models/ParkedVehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GarageReturn.Models
{
    public class ParkedVehicle
    {

        public int Id { get; set; }

        [Required (ErrorMessage = "Vehicle type is required")]
        public VehiclesTypes VehicleTypes { get; set; }

        [Required(ErrorMessage = "Please , specify the Registration number")]
        public string RegNum { get; set; }

        [Required(ErrorMessage = "Please , specify the color of the vehicle")]

        public string Color { get; set; }

        [Required(ErrorMessage = "Please , specify the brand of the vehicle")]
        public string Brand { get; set; }

        [Required(ErrorMessage = "Please , specify the model")]
        public string Model { get; set; }

        [Required(ErrorMessage = "Please , specify the number of wheels")]
        public int NumberOfWheels { get; set; }

      
        public DateTime ParkedTime { get; set; }
      
    }
    public enum VehiclesTypes
    {
        Bus,
        Car,
        Motorcycle,
        Truck
    }

}

GarageReturn/GarageReturn/Models/ReceiptViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GarageReturn.Models
{
    public class ReceiptViewModel
    {
      
    

        public ReceiptViewModel(int id, string regNum, string vehicleType, DateTime parkedTime, DateTime nowTime, string name)
        {
            Id = id;
            RegNum = regNum;
            VehicleType = vehicleType;
            NowTime = nowTime;
            Name = name;

            ParkedTime = parkedTime;
            TimeSpan ts = NowTime - ParkedTime;
            TotalTime = $"{Math.Floor(ts.TotalDays)} days, {ts.Hours} hours and {ts.Minutes} minutes.";
               Price = (ts.TotalMinutes ) * 5;
  
       
        }

        public ReceiptViewModel(Member member)
        {
            this.member = member;

        }


     

        public int Id { get; set; }

        public string RegNum { get; set; }

        public string VehicleType { get; set; }

        [Display(Name = "Check out time")]
        [UIHint("DateFormat")]


        public DateTime NowTime { get; set; }

        [Display(Name = "Arrival time")]
        [UIHint("DateFormat")]
        public DateTime ParkedTime { get; set; }

        public double Price { get; set; }

        [Display(Name = "Total time")]
        public string TotalTime { get; set; }
        public Member member;
        public string Name;


    }
    
}

GarageReturn/GarageReturn/Controllers/ParkedVehiclesController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using GarageReturn.DataAccessLayer;
using GarageReturn.Models;

namespace GarageReturn.Controllers
{
    public class ParkedVehiclesController : Controller
    {


        private StorageContext db = new StorageContext();


      
        //GET: ParkedVehicles
       
            public ActionResult Index(string sortOrder)

        {
            
            var park = db.Members.ToList();
            var parkedVehicle = db.vehicles.ToList();

            if (sortOrder == "Ascending")
            {
                parkedVehicle = parkedVehicle.OrderBy(s => s.RegNum).ToList();
            }

            else if (sortOrder == "Descending")
            {
                parkedVehicle = parkedVehicle.OrderByDescending(s => s.RegNum).ToList();
            }


            List<IndexVehicle> iv = new List<IndexVehicle>();

       

            foreach (ParkedVehicle e in parkedVehicle.ToList())

            {
                iv.Add(new IndexVehicle(e));
              
            }
            return View(iv);
        }
        [HttpPost]
        public ActionResult Search(string search)
        {
            

        List<IndexVehicle> iv = new List<IndexVehicle>();

         

            foreach (ParkedVehicle e in db.vehicles.Where(s => s.RegNum.Contains(search) || s.VehiclesType.Name.Contains(search) || s.Color.Contains(search) || s.Member.FirstName.Contains(search)).ToList() )

            {
                

                iv.Add(new IndexVehicle(e));
            }

            return View("Index", iv);


        }



        // GET: ParkedVehicles/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.vehicles.Find(id);
            Park park = new Park(parkedVehicle.Brand,parkedVehicle.Color, parkedVehicle.Model, parkedVehicle.ParkedTime, parkedVehicle.RegNum, parkedVehicle.NumberOfWheels,parkedVehicle.VehiclesTypeId , parkedVehicle.MemberId);


            //VehiclesViewModel s = new VehiclesViewModel(parkedVehicle.Id, parkedVehicle.RegNum, parkedVehicle.VehicleTypes, DateTime.Now, parkedVehicle.ParkedTime); 


            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }

            parkedVehicle.Color = park.Color;
            parkedVehicle.Brand = park.Brand;
            parkedVehicle.Model = park.Model;
            parkedVehicle.NumberOfWheels = park.NumberOfWheels;
            parkedVehicle.RegNum = park.RegNum;
            parkedVehicle.MemberId = park.MemberId;
            parkedVehicle.VehiclesTypeId = park.VehicleTypesId;
            parkedVehicle.ParkedTime = DateTime.Now;
            return View(park);
        }

            // GET: ParkedVehicles/Create

            public ActionResult Create()
            {
            var members = db.Members.ToList();

            Park park = new Park();
        park.ListMembers = members.Select(x => new SelectListItem()
            {
                Text = x.FirstName,
                Value = x.Id.ToString(),
            });

            var vehiclesTypes = db.VehicleTypes.ToList();

            park.ListVehicleTypes = vehiclesTypes.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });


            return View(park);
        }
          




        // POST: ParkedVehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RegNum,Color,Brand,Model,NumberOfWheels,ParkedTime, MemberId,VehicleTypesId")] Park park)
        {
          

        var parkedVehicle = new ParkedVehicle();

            if (ModelState.IsValid)
            {
                parkedVehicle.Color = park.Color;
                parkedVehicle.Brand = park.Brand;
                parkedVehicle.Model = park.Model;
                parkedVehicle.NumberOfWheels = park.NumberOfWheels;
                parkedVehicle.RegNum = park.RegNum;
                parkedVehicle.MemberId = park.MemberId;
                parkedVehicle.VehiclesTypeId = park.VehicleTypesId;
                parkedVehicle.ParkedTime = DateTime.Now;
                db.vehicles.Add(parkedVehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(park);

            //VehiclesViewModel s = new VehiclesViewModel(parkedVehicle.Id, parkedVehicle.RegNum, parkedVehicle.VehicleTypes, DateTime.Now, parkedVehicle.ParkedTime); 

        }








        // GET: ParkedVehicles/Edit/5
        public ActionResult Edit(int? id)
        {
     
 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.vehicles.Find(id);
            EditViewModel ed = new EditViewModel(parkedVehicle.Id, parkedVehicle.Color, parkedVehicle.Brand, parkedVehicle.Color, parkedVehicle.NumberOfWheels , parkedVehicle.RegNum);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            return View(ed);
        }

        // POST: ParkedVehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken] 
        public ActionResult Edit([Bind(Include = "Id,Color,Brand,Model,NumberOfWheels,RegNum ")] EditViewModel editv )
        {


       
            if (ModelState.IsValid)
            {

                ParkedVehicle pv = db.vehicles.FirstOrDefault(x => x.Id == editv.Id);

                pv.RegNum = editv.RegNum;
                pv.Brand = editv.Brand;
                pv.Model = editv.Model;
                pv.NumberOfWheels = editv.NumberOfWheels  ;
                pv.RegNum = editv.RegNum;


                

                //db.Entry(editv).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(editv);
        }

        // GET: ParkedVehicles/Delete/5
        public ActionResult Delete(int? id )
        {

            var park = db.Members.ToList();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.vehicles.Find(id);



            if (parkedVehicle == null)
            {
               
                return HttpNotFound();
            }
          

            VehiclesViewModel v = new VehiclesViewModel (parkedVehicle.Id, parkedVehicle.RegNum, parkedVehicle.VehiclesType.Name, parkedVehicle.ParkedTime, DateTime.Now );

            return View(v);
        }

        // POST: ParkedVehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]


        public ActionResult DeleteConfirmed(int id)
        {
            

            ParkedVehicle parkedVehicle = db.vehicles.Find(id);

            
            ReceiptViewModel s = new ReceiptViewModel(parkedVehicle.Id, parkedVehicle.RegNum,parkedVehicle.VehiclesType.Name,parkedVehicle.ParkedTime,DateTime.Now ,  parkedVehicle.Member.FirstName);
            var park = db.Members.ToList();



            db.vehicles.Remove(parkedVehicle);

            db.SaveChanges();

            return View("ReceiptView" ,s);

           
        }
        

        
     




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GarageReturn/GarageReturn/Views/ParkedVehicles/Create.cshtml
@model GarageReturn.Models.Park

@{
    ViewBag.Title = "Park";
}

<h2>Park</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ParkedVehicle</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group">
            @Html.LabelFor(model => model.VehicleTypes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.VehicleTypes, " ", new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.VehicleTypes, " ", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.RegNum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RegNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RegNum, " ", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumberOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumberOfWheels, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumberOfWheels, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ListMembers, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.MemberId, Model.ListMembers, "  ", new { @class = "form-control " })

            @Html.ValidationMessageFor(model => model.ListMembers)
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ListVehicleTypes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.VehicleTypesId, Model.ListVehicleTypes, "  ", new { @class = "form-control " })
            @Html.ValidationMessageFor(model => model.ListVehicleTypes)
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Park" class="btn btn-default" />
        </div>
    </div>
</div>
 }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }



    @*<div class="display-field">
            @Html.DropDownListFor(m => m.StatePick, Model.StateList, new { OnChange = "state.value = this.value;" })
            @Html.EditorFor(model => model.state)
            @Html.ValidationMessageFor(model => model.StateList)
        </div>*@



    @*<div class="form-group">
            @Html.LabelFor(model => model.MemberId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>*@



    @*<div class="form-group">

            @Html.DropDownListFor(m => Model.MemberId, Model.ListMembers, new { OnChange = "member.value = this.value;" }))
            @Html.EditorFor(Model => Model.Member)
            @Html.ValidationMessageFor(model => model.ListMembers)
        </div>*@

GarageReturn/GarageReturn/Views/ParkedVehicles/Delete.cshtml
@model GarageReturn.Models.VehiclesViewModel

@{
    ViewBag.Title = "Check out";
}

<h2>check out</h2>

<h3>Are you sure you want to check out this?</h3>
<div>
    <h4>ParkedVehicle</h4>
    <hr />
    <dl class="dl-horizontal">


        @*<dt>
            @Html.DisplayNameFor(model => model.member.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.member.FirstName)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNum)
        </dd>
        <dt>
        <dd>
            @Html.DisplayFor(model => model.ParkedTime)
        </dd>



        <dd>
            @Html.DisplayFor(model => model.NowTime)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>**@



    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="check out" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GarageReturn/GarageReturn/Views/ParkedVehicles/Details.cshtml
@model GarageReturn.Models.Park

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ParkedVehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.VehiclesType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehiclesType)
        </dd>*@


        <dt>
            @Html.DisplayNameFor(model => model.MemberId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>


        <dd>
            @Html.DisplayFor(model => model.ParkedTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParkedTime)
        </dt>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GarageReturn/GarageReturn/Views/ParkedVehicles/Edit.cshtml
@model GarageReturn.Models.EditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ParkedVehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @*<div class="form-group">
            @Html.LabelFor(model => model.VehiclesType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehiclesType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehiclesType, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.RegNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfWheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfWheels, "", new { @class = "text-danger" })
            </div>

            

            </div>
        </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
     
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GarageReturn/GarageReturn/Views/ParkedVehicles/Index.cshtml
@model IEnumerable<GarageReturn.Models.IndexVehicle>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Park New", "Create" )
</p>

@using (Html.BeginForm("Search", "ParkedVehicles", FormMethod.Post))
{
   @Html.TextBox("search")
    
    <input type="submit" value="Search" />
}


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.VehType)
        </th>


        <th>
            @Html.ActionLink("RegNum", "Index", new { sortOrder = "Descending" })
        </th>

        @*<th>


            @Html.DisplayNameFor(model => model.RegNum)

        </th>*@


        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ParkedTime)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>


        <td>
            @Html.DisplayFor(modelItem => item.VehType)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.RegNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ParkedTime)
        </td>


        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfWheels)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("check out", "Delete", new { id = item.Id })
        </td>
    </tr>
    }

</table>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GarageReturn/GarageReturn/Views/ParkedVehicles/ReceiptView.cshtml
@model GarageReturn.Models.ReceiptViewModel

@{
    ViewBag.Title = "ReceiptView";
}

<h2>ReceiptView</h2>

<div>
    <h4>ReceiptViewModel</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParkedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParkedTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NowTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NowTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>





    </dl>
</div>
<p>

<p>Click the button to print the current page.</p>

<button onclick="myFunction()">Print out the receipt</button>

<script>
    function myFunction() {
        window.print();
    }
</script>

<p>
@Html.ActionLink("Back to List", "Index")
</p>